# Generated by Django 5.2.5 on 2025-12-17 18:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(help_text='Insira o nome da rua', max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(help_text='Insira o número do endereço', max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(help_text='Insira o bairro', max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Insira a cidade', max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Insira o estado', max_length=50, verbose_name='Estado')),
                ('cep', models.CharField(help_text='Insira o CEP', max_length=10, verbose_name='CEP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quarto', models.CharField(help_text='Insira o número do quarto', max_length=10, verbose_name='Número do Quarto')),
                ('tipo_quarto', models.CharField(help_text='Insira o tipo do quarto (e.g., solteiro, casal, suíte)', max_length=50, verbose_name='Tipo do Quarto')),
                ('preco_diaria', models.DecimalField(decimal_places=2, help_text='Insira o preço da diária do quarto', max_digits=10, verbose_name='Preço da Diária')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ManyToManyField(related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', help_text='Insira o nome do cliente', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome')),
                ('cpf', models.CharField(default='', help_text='Insira o cpf do cliente', max_length=11, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, help_text='Insira o telefone do cliente', max_length=11, null=True, verbose_name='Telefone')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('endereco', models.ForeignKey(help_text='Insira o endereço do cliente', on_delete=django.db.models.deletion.CASCADE, to='registro.enderecocliente', verbose_name='Endereço')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(help_text='Insira a data de entrada da reserva', verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(help_text='Insira a data de saída da reserva', verbose_name='Data de Saída')),
                ('quantidade_pessoas', models.IntegerField(help_text='Insira a quantidade de pessoas para a reserva', verbose_name='Quantidade de Pessoas')),
                ('valor_reserva', models.DecimalField(decimal_places=2, help_text='Insira o valor total da reserva', max_digits=10, verbose_name='Valor da Reserva')),
                ('cliente_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.cliente')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.quarto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
